/*
  Warnings:

  - The values [STANDARD_ACCOUNT_CREATED] on the enum `AuditEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AuditEventType_new" AS ENUM ('PROJECT_DATA_UPDATED', 'PROJECT_ASSIGNEE_UPDATED', 'PROJECT_STATUS_UPDATED', 'PROJECT_STEP_UPDATED', 'USER_DELEGATION_CREATED', 'USER_DELEGATION_CANCELLED', 'PROJECT_CANCELLATION_CREATED', 'PROJECT_CANCELLATION_APPROVED', 'PROJECT_CANCELLATION_REJECTED', 'CONTRACT_NUMBER_CREATED', 'CONTRACT_NUMBER_CANCELLED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REMOVED', 'UNIT_STAFF_ADDED', 'UNIT_STAFF_REMOVED', 'REGISTRATION_REQUESTED', 'REGISTRATION_APPROVED', 'REGISTRATION_REJECTED', 'USER_CREATED');
ALTER TABLE "audit_events" ALTER COLUMN "event_type" TYPE "AuditEventType_new" USING ("event_type"::text::"AuditEventType_new");
ALTER TYPE "AuditEventType" RENAME TO "AuditEventType_old";
ALTER TYPE "AuditEventType_new" RENAME TO "AuditEventType";
DROP TYPE "public"."AuditEventType_old";
COMMIT;
