-- AlterEnum
ALTER TYPE "AuditLogType" ADD VALUE 'USER_MANAGEMENT';

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'USER_ROLE_ASSIGNED';
ALTER TYPE "AuditEventType" ADD VALUE 'USER_ROLE_REMOVED';
ALTER TYPE "AuditEventType" ADD VALUE 'UNIT_STAFF_ADDED';
ALTER TYPE "AuditEventType" ADD VALUE 'UNIT_STAFF_REMOVED';

-- AlterEnum
ALTER TYPE "AuditTargetType" ADD VALUE 'USER';
